openapi: 3.0.3
info:
  title: Event API
  version: "1.0"
paths:
  /sessions:
    get:
      summary: セッション情報の一覧を取得
      operationId: lisetSessions
      responses:
        '200':
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Session'
  /sessions/{sessionId}/comments:
    parameters: 
      -
        in: path
        name:  sessionId
        required: true
        schema:
          type: string
          example: 1
    get:
      summary: セッションに対するコメントの一覧を取得
      operationId: listSessionComments
      responses:
        '200':
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Comment'
    post:
      summary: セッションにコメントを追加
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentRequest'
      responses:
        '201':
          description: 正常系
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: バリデーションエラー
        '404':
          description: 指定されたセッションが存在しない場合
  /questionnaires:
    get:
      summary: アンケートの一覧を取得
      operationId: listQuestionnaires
      responses:
        '200':
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  questionnaires:
                    type: array
                    items:
                      $ref: '#/components/schemas/Questionnaire'
                    example:
                      - questionnaireId: 1
                        title: 好きなプログラミング言語
                        content: 好きなプログラミング言語は何ですか？
                        type: choice
                        choices:
                          - COBOL
                          - Acess VBA
                          - Excel VBA
                      - questionnaireId: 2
                        title: 自由に意見下さい
                        content: なんでも書いていいよ
                        type: free                        
  /questionnaires/{questionnaireId}/choices:
    parameters: 
      -
        in: path
        name:  questionnaireId
        required: true
        schema:
          type: string
          example: 1  
    put:
      summary: アンケートの選択肢を追加
      operationId: putQuestionnaireChoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Excel VBA
                  minimum: 1
                  maxLength: 50
      responses:
        '200':
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  title::
                    type: string
                    example: Excel VBA
        '400':
          description: バリデーションエラー
        '404':
          description: 指定されたアンケートが存在しない場合                         
  /questionnaires/{questionnaireId}/answers:
    parameters: 
      -
        in: path
        name:  questionnaireId
        required: true
        schema:
          type: string
          example: 1  
    post:
      summary: アンケートに回答
      operationId: createQuestionnaireAnswer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAnswerRequest"
            examples:
              選択式のアンケートの場合:
                value:
                  participantId: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
                  participantName: 参加者1
                  choice: COBOL
              自由記述のアンケートの場合:
                value:
                  participantId: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
                  participantName: 参加者1
                  content: 良かったです
      responses:
        '200':
          description: 正常系
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'                                 
              examples:
                選択式のアンケートの場合:
                  value:
                      participantId: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
                      participantName: 参加者1
                      answerAt: 2024-07-31T14:10:00+09:00
                      choice: COBOL
                自由記述のアンケートの場合:
                  value:                    
                      participantId: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
                      participantName: 参加者1
                      answerAt: 2024-07-31T14:10:00+09:00
                      content: 良かったです
        '400':
          description: バリデーションエラー
        '404':
          description: 指定されたアンケートが存在しない場合                      
    get:
      summary: アンケートの回答一覧取得
      operationId: listQuestionnaireAnswers
      responses:
        '200':
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  answers::
                    type: array
                    items:
                      $ref: '#/components/schemas/Answer'
              examples:
                選択式のアンケートの場合:
                  value:
                    answers:
                      - participantId: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
                        participantName: 参加者1
                        answerAt: 2024-07-31T14:10:00+09:00
                        choice: COBOL
                      - participantId: 1f4ebfc6-0ae0-42e3-8fa0-a9fabd5d474b
                        participantName: 参加者2
                        answerAt: 2024-07-31T14:11:00+09:00
                        choice: Access VBA
                自由記述のアンケートの場合:
                  value:
                    answers:
                      - participantId: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
                        participantName: 参加者1
                        answerAt: 2024-07-31T14:10:00+09:00
                        content: 良かったです
                      - participantId: 1f4ebfc6-0ae0-42e3-8fa0-a9fabd5d474b
                        participantName: 参加者2
                        answerAt: 2024-07-31T14:11:00+09:00
                        content: パチパチパチ888
components:
  schemas:
    Answer:
      type: object
      properties:
        participantId:
          type: string
        participantName:
          type: string
        answerAt:
          type: string
          format: date-time          
        choice:
          type: string
        content:
          type: string
      required:
        - participantId
        - participantName
        - answerAt
    Comment:
      type: object
      properties:
        sessionId:
          type: integer
          example: 1
        commentAt:
          type: string
          format: date-time
          example: 2024-07-31T14:10:00+09:00
        participantId:
          type: string
          example: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
        participantName:
          type: string
          example: 参加者1
        comment:
          type: string
          example: めっちゃわかりやすい！
    CreateAnswerRequest:
      type: object
      properties:
        participantId:
          type: string
          example: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
          minimum: 36
          maximum: 36
        participantName:
          type: string
          example: 参加者1
          minimum: 1
          maximum: 50
        choice:
          type: string
          example: COBOL
          minimum: 1
          maximum: 50
        content:
          type: string
          example: 良かったです
          minimum: 1
          maximum: 400
      required:
        - participantId
        - participantName            
    CreateCommentRequest:
      type: object
      properties:
        participantId:
          type: string
          example: 9d5f3a5f-1bf9-4f3f-987f-37137a666992
          minimum: 36
          maximum: 36
        participantName:
          type: string
          example: 参加者1
          minimum: 1
          maximum: 50
        comment:
          type: string
          example: めっちゃわかりやすい！
          minimum: 1
          maximum: 200
    Questionnaire:
      type: object
      properties:
        questionnaireId:
          type: integer
        title:
          type: string
        content:
          type: string
        type:
          type: string
          enum:
            - choice
            - free
        choices:
          type: array
          items:
            type: string
    Session:
      type: object
      properties:
        sessionId:
          type: integer
          example: 1
        startAt:
          type: string
          format: date-time
          example: 2024-07-31T13:50:00+09:00
        endAt:
          type: string
          format: date-time
          example: 2024-07-31T14:10:00+09:00
        speakerCompany:
          type: string
          example: クラスメソッド株式会社
        speakerDepartment:
          type: string
          example: CX事業本部
        speakerTitle:
          type: string
          example: エンジニア
        speakerName:
          type: string
          example: めそ子
        sessionTitle:
          type: string
          example: 超すごい登壇
        description:
          type: string
          example: Auroraについてあますところなく解説してくれるセッションです          
